sudo: false
language: python
python:
        - 3.5
install:
        - python setup.py install
        - pip install -r requirements-test.txt
script:
        - py.test tests
notifications:
        email: false
